// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID           int32
	Name         string
	Email        string
	Phone        pgtype.Text
	Message      string
	SourceDomain string
	TenantID     int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Tenant struct {
	ID          int32
	Name        string
	Slug        string
	Email       string
	CompanyUrl  pgtype.Text
	Description pgtype.Text
	Timezone    pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TenantConfig struct {
	ID          int32
	TenantID    int32
	DisplayName string
	ConfigName  string
	Value       string
	ValueType   string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           int32
	UserName     string
	Fname        pgtype.Text
	Lname        pgtype.Text
	Email        string
	PasswordHash string
	TenantID     int32
	Roles        []string
	Scopes       []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
