// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfigsByTenantSlug = `-- name: GetConfigsByTenantSlug :many
SELECT tc.id, tc.tenant_id, tc.display_name, tc.config_name, tc.value, tc.value_type, tc.description, tc.created_at, tc.updated_at FROM tenant_configs tc
JOIN tenants t ON tc.tenant_id = t.id
WHERE t.slug = $1
ORDER BY tc.config_name
`

func (q *Queries) GetConfigsByTenantSlug(ctx context.Context, slug string) ([]TenantConfig, error) {
	rows, err := q.db.Query(ctx, getConfigsByTenantSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantConfig
	for rows.Next() {
		var i TenantConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DisplayName,
			&i.ConfigName,
			&i.Value,
			&i.ValueType,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContact = `-- name: GetContact :one
SELECT id, name, email, phone, message, source_domain, tenant_id, status, created_at, updated_at FROM contacts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContact(ctx context.Context, id int32) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.SourceDomain,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, company_url, description, timezone, created_at, updated_at FROM tenants
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CompanyUrl,
		&i.Description,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT id, user_name, password_hash, tenant_id, roles, scopes
FROM users
where email = $1 LIMIT 1
`

type GetUserForAuthRow struct {
	ID           int32
	UserName     string
	PasswordHash string
	TenantID     int32
	Roles        []string
	Scopes       []string
}

func (q *Queries) GetUserForAuth(ctx context.Context, email string) (GetUserForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserForAuth, email)
	var i GetUserForAuthRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.TenantID,
		&i.Roles,
		&i.Scopes,
	)
	return i, err
}

const getUserWithTenantByUserName = `-- name: GetUserWithTenantByUserName :one
SELECT 
    u.id, u.user_name, u.fname, u.lname, u.email, u.roles, u.scopes,
    t.slug AS tenant_slug,
    t.name AS tenant_name
FROM users u
JOIN tenants t ON u.tenant_id = t.id
WHERE user_name = $1 LIMIT 1
`

type GetUserWithTenantByUserNameRow struct {
	ID         int32
	UserName   string
	Fname      pgtype.Text
	Lname      pgtype.Text
	Email      string
	Roles      []string
	Scopes     []string
	TenantSlug string
	TenantName string
}

func (q *Queries) GetUserWithTenantByUserName(ctx context.Context, userName string) (GetUserWithTenantByUserNameRow, error) {
	row := q.db.QueryRow(ctx, getUserWithTenantByUserName, userName)
	var i GetUserWithTenantByUserNameRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Fname,
		&i.Lname,
		&i.Email,
		&i.Roles,
		&i.Scopes,
		&i.TenantSlug,
		&i.TenantName,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :one
INSERT INTO contacts (
    name, email, phone, message, source_domain, 
    tenant_id, 
    status
) VALUES (
    $1, $2, $3, $4, $5, 
    (SELECT id FROM tenants WHERE slug = $6), 
    'new'
)
RETURNING id, name, email, phone, message, source_domain, tenant_id, status, created_at, updated_at
`

type InsertContactParams struct {
	Name         string
	Email        string
	Phone        pgtype.Text
	Message      string
	SourceDomain string
	Slug         string
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, insertContact,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Message,
		arg.SourceDomain,
		arg.Slug,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.SourceDomain,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactsByTenantSlug = `-- name: ListContactsByTenantSlug :many
SELECT
    c.name, c.email, c.phone, c.message, c.status, c.created_at, c.updated_at
FROM contacts c
JOIN tenants t ON c.tenant_id = t.id
WHERE t.slug = $1
ORDER BY c.created_at DESC
`

type ListContactsByTenantSlugRow struct {
	Name      string
	Email     string
	Phone     pgtype.Text
	Message   string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListContactsByTenantSlug(ctx context.Context, slug string) ([]ListContactsByTenantSlugRow, error) {
	rows, err := q.db.Query(ctx, listContactsByTenantSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsByTenantSlugRow
	for rows.Next() {
		var i ListContactsByTenantSlugRow
		if err := rows.Scan(
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, company_url, description, timezone, created_at, updated_at FROM tenants
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CompanyUrl,
			&i.Description,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantSlug = `-- name: ListUsersByTenantSlug :many
SELECT
    u.id, u.user_name, u.fname, u.lname, u.email, u.roles, u.scopes, u.created_at
FROM users u
JOIN tenants t ON u.tenant_id = t.id
WHERE t.slug = $1
ORDER BY u.created_at DESC
`

type ListUsersByTenantSlugRow struct {
	ID        int32
	UserName  string
	Fname     pgtype.Text
	Lname     pgtype.Text
	Email     string
	Roles     []string
	Scopes    []string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListUsersByTenantSlug(ctx context.Context, slug string) ([]ListUsersByTenantSlugRow, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByTenantSlugRow
	for rows.Next() {
		var i ListUsersByTenantSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Fname,
			&i.Lname,
			&i.Email,
			&i.Roles,
			&i.Scopes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactStatus = `-- name: UpdateContactStatus :one
UPDATE contacts
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, email, phone, message, source_domain, tenant_id, status, created_at, updated_at
`

type UpdateContactStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContactStatus, arg.ID, arg.Status)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.SourceDomain,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
