// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Message      string             `json:"message"`
	SourceDomain string             `json:"source_domain"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
