// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    name, email, phone, message, source_domain, status
) VALUES (
    $1, $2, $3, $4, $5, 'new'
)
RETURNING id, name, email, phone, message, source_domain, status, created_at, updated_at
`

type CreateContactParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Message      string      `json:"message"`
	SourceDomain string      `json:"source_domain"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Message,
		arg.SourceDomain,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.SourceDomain,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, name, email, phone, message, source_domain, status, created_at, updated_at FROM contacts
WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id int32) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.SourceDomain,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT 
    u.id, u.user_name, u.fname, u.lname, u.email, u.password_hash, u.roles, u.scopes, u.created_at, u.updated_at, u.tenant_id, 
    t.slug AS tenant_slug 
FROM users u
JOIN tenants t ON u.tenant_id = t.id
WHERE u.email = $1 LIMIT 1
`

type GetUserRow struct {
	ID           int32              `json:"id"`
	UserName     string             `json:"user_name"`
	Fname        pgtype.Text        `json:"fname"`
	Lname        pgtype.Text        `json:"lname"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Roles        []string           `json:"roles"`
	Scopes       []string           `json:"scopes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TenantID     int32              `json:"tenant_id"`
	TenantSlug   string             `json:"tenant_slug"`
}

func (q *Queries) GetUser(ctx context.Context, email string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Fname,
		&i.Lname,
		&i.Email,
		&i.PasswordHash,
		&i.Roles,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.TenantSlug,
	)
	return i, err
}
