// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	GetContact(ctx context.Context, id int32) (Contact, error)
	GetUser(ctx context.Context, email string) (GetUserRow, error)
}

var _ Querier = (*Queries)(nil)
