// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    name, email, phone, message, source_domain, status
) VALUES (
    $1, $2, $3, $4, $5, 'new'
)
RETURNING id, name, email, phone, message, source_domain, status, created_at, updated_at
`

type CreateContactParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Message      string      `json:"message"`
	SourceDomain string      `json:"source_domain"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Message,
		arg.SourceDomain,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.SourceDomain,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
